plugins {
    id 'com.android.application'
}

android {
    namespace 'com.memorydrawer.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.memorydrawer.app"
        minSdk 29
        targetSdk 35
        versionCode 20
        versionName "2.0.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
